import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';

// Supported languages with their native names
export const SUPPORTED_LANGUAGES = {
  en: { name: 'English', nativeName: 'English', flag: '🇺🇸' },
  ar: { name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', rtl: true },
  zh: { name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  es: { name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  fr: { name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  de: { name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  ja: { name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  ko: { name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  pt: { name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  ru: { name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  tr: { name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
} as const;

export type LanguageCode = keyof typeof SUPPORTED_LANGUAGES;

// Complete English translations (default)
const enTranslations: Record<string, string> = {
  // Navigation
  'nav.adminPanel': 'Admin Panel',
  'nav.welcome': 'Welcome',
  'nav.dashboard': 'Dashboard',
  'nav.licenses': 'Licenses',
  'nav.security': 'Security',
  'nav.settings': 'Settings',
  'nav.orders': 'Orders',
  'nav.backToSite': 'Back to Site',
  'nav.signOut': 'Sign out',
  'nav.pricing': 'Pricing',
  'nav.download': 'Download',
  'nav.backToHome': 'Back to Home',
  
  // Landing Page
  'landing.badge': 'ADVANCED COLOR DETECTION SYSTEM',
  'landing.tagline': 'Professional-grade color tracking and automated mouse control for Windows.',
  'landing.precision': 'Precision. Speed. Control.',
  'landing.download': 'DOWNLOAD FOR WINDOWS',
  'landing.version': 'v1.0.0 • Windows 10/11 • 64-bit',
  'landing.featuresTitle': 'SYSTEM // FEATURES',
  'landing.featuresSubtitle': 'Engineered for performance, designed for precision',
  'landing.feature.colorDetection': 'Color Detection',
  'landing.feature.colorDetectionDesc': 'Advanced pixel-level color tracking with customizable tolerance and multi-color support.',
  'landing.feature.instantResponse': 'Instant Response',
  'landing.feature.instantResponseDesc': 'Sub-millisecond detection with optimized algorithms for real-time performance.',
  'landing.feature.regionSelection': 'Region Selection',
  'landing.feature.regionSelectionDesc': 'Define specific screen regions to optimize performance and reduce false positives.',
  'landing.feature.fullControl': 'Full Control',
  'landing.feature.fullControlDesc': 'Adjustable click rates, tracking sensitivity, and customizable hotkeys.',
  'landing.feature.multiMonitor': 'Multi-Monitor',
  'landing.feature.multiMonitorDesc': 'Seamless support for multi-monitor setups with independent region tracking.',
  'landing.feature.secureLicensing': 'Secure Licensing',
  'landing.feature.secureLicensingDesc': 'Hardware-locked activation with encrypted license validation.',
  'landing.stats.responseTime': 'RESPONSE TIME',
  'landing.stats.fpsTracking': 'FPS TRACKING',
  'landing.stats.accuracy': 'ACCURACY',
  'landing.stats.support': 'SUPPORT',
  'landing.cta.title': 'Ready to Dominate?',
  'landing.cta.subtitle': 'Download KSA,Boom now and experience the next level of color tracking technology.',
  'landing.cta.button': 'GET STARTED',
  'landing.footer': '© 2024 KSA,Boom. All rights reserved.',
  
  // Pricing Page
  'pricing.badge': 'SUBSCRIPTION PLANS',
  'pricing.title': 'Choose Your Plan',
  'pricing.subtitle': 'Select the subscription that fits your needs. All plans include full access to KSA,Boom features.',
  'pricing.weekly': 'Weekly Plan',
  'pricing.monthly': 'Monthly Plan',
  'pricing.yearly': 'Yearly Plan',
  'pricing.weeklyDesc': 'Weekly subscription',
  'pricing.monthlyDesc': 'Monthly subscription',
  'pricing.yearlyDesc': 'Yearly subscription',
  'pricing.mostPopular': 'Most Popular',
  'pricing.getStarted': 'Get Started',
  'pricing.paymentInfo': 'Payment Information',
  'pricing.paymentDesc': 'After placing your order, our team will contact you via email to verify payment. Once confirmed, your license key will be generated and sent to your email address.',
  'pricing.contactEmail': 'For payment inquiries, contact us at:',
  'pricing.orderPlaced': 'Order Placed Successfully!',
  'pricing.orderNumber': 'Order Number',
  'pricing.orderConfirmation': 'We have received your order. Our team will contact you at the email address you provided to verify payment.',
  'pricing.whatNext': 'What happens next?',
  'pricing.step1': 'Our team will contact you via email',
  'pricing.step2': 'Complete payment verification',
  'pricing.step3': 'Receive your license key',
  'pricing.placeOrder': 'Place Order',
  'pricing.processing': 'Processing...',
  'pricing.yourEmail': 'Your Email',
  'pricing.yourName': 'Your Name',
  'pricing.enterEmail': 'Enter your email address',
  'pricing.enterName': 'Enter your name',
  'pricing.close': 'Close',
  
  // Plan Features
  'plan.feature.fullAccess': 'Full access to all features',
  'plan.feature.colorDetection': 'Advanced color detection',
  'plan.feature.multiMonitor': 'Multi-monitor support',
  'plan.feature.customHotkeys': 'Custom hotkeys',
  'plan.feature.prioritySupport': 'Priority support',
  'plan.feature.updates': 'Free updates',
  'plan.feature.hwLock': 'Hardware-locked license',
  'plan.feature.emailSupport': 'Email support',
  'plan.feature.weeklyUpdates': 'Weekly updates',
  'plan.feature.monthlyUpdates': 'Monthly updates',
  'plan.feature.yearlyUpdates': 'Yearly updates',
  'plan.feature.basicSupport': 'Basic support',
  'plan.feature.premiumSupport': 'Premium support',
  'plan.feature.dedicatedSupport': 'Dedicated support',
  'plan.feature.allFeatures': 'All premium features',
  'plan.feature.unlimitedUse': 'Unlimited use',
  'plan.feature.fastResponse': 'Fast response time',
  'plan.feature.regionSelection': 'Region selection',
  'plan.feature.clickAutomation': 'Click automation',
  'plan.feature.bestValue': 'Best value',
  
  // Download Page
  'download.title': 'Download KSA,Boom',
  'download.subtitle': 'Get the latest version of KSA,Boom for Windows',
  'download.downloadNow': 'Download Now',
  'download.version': 'Version',
  'download.size': 'Size',
  'download.platform': 'Platform',
  'download.requirements': 'System Requirements',
  'download.os': 'Operating System',
  'download.osValue': 'Windows 10/11 (64-bit)',
  'download.processor': 'Processor',
  'download.processorValue': 'Intel Core i3 or equivalent',
  'download.memory': 'Memory',
  'download.memoryValue': '4 GB RAM',
  'download.storage': 'Storage',
  'download.storageValue': '100 MB available space',
  'download.installation': 'Installation Guide',
  'download.step1': 'Download the installer',
  'download.step2': 'Run the .exe file',
  'download.step3': 'Follow the installation wizard',
  'download.step4': 'Enter your license key when prompted',
  'download.noLicense': 'Don\'t have a license key?',
  'download.getPlan': 'Get a subscription plan',
  'download.validateLicense': 'Validate License',
  'download.enterLicenseKey': 'Enter your license key',
  'download.validate': 'Validate',
  'download.validating': 'Validating...',
  'download.licenseValid': 'License Valid',
  'download.licenseInvalid': 'License Invalid',
  'download.expiresOn': 'Expires on',
  'download.activationsRemaining': 'activations remaining',
  'download.downloadStarting': 'Download will start shortly...',
  'download.contactAdmin': 'Please contact admin to receive the application file.',
  
  // Dashboard
  'dashboard.title': 'CONTROL // PANEL',
  'dashboard.subtitle': 'System overview and monitoring',
  'dashboard.totalLicenses': 'Total Licenses',
  'dashboard.downloads': 'Downloads',
  'dashboard.securityEvents': 'Security Events',
  'dashboard.pendingOrders': 'Pending Orders',
  'dashboard.revenue': 'Revenue',
  'dashboard.active': 'Active',
  'dashboard.pending': 'Pending',
  'dashboard.expired': 'Expired',
  'dashboard.revoked': 'Revoked',
  'dashboard.recentActivations': 'Recent Activations',
  'dashboard.recentActivationsDesc': 'Latest license activation attempts',
  'dashboard.securityAlerts': 'Security Alerts',
  'dashboard.securityAlertsDesc': 'Unresolved security events',
  'dashboard.noRecentActivations': 'No recent activations',
  'dashboard.noSecurityEvents': 'No unresolved security events',
  'dashboard.success': 'Success',
  'dashboard.failed': 'Failed',
  'dashboard.unknownDevice': 'Unknown Device',
  'dashboard.today': 'today',
  'dashboard.critical': 'critical',
  'dashboard.securityEventsLabel': 'Security events',
  
  // Orders
  'orders.title': 'ORDER // MANAGEMENT',
  'orders.subtitle': 'Manage customer orders and subscriptions',
  'orders.allOrders': 'All Orders',
  'orders.pendingOrders': 'Pending',
  'orders.confirmedOrders': 'Confirmed',
  'orders.cancelledOrders': 'Cancelled',
  'orders.orderNumber': 'Order #',
  'orders.customer': 'Customer',
  'orders.plan': 'Plan',
  'orders.amount': 'Amount',
  'orders.status': 'Status',
  'orders.date': 'Date',
  'orders.actions': 'Actions',
  'orders.confirm': 'Confirm',
  'orders.cancel': 'Cancel',
  'orders.noOrders': 'No orders found',
  'orders.confirmOrder': 'Confirm Order',
  'orders.confirmOrderDesc': 'This will generate a license key and send it to the customer.',
  'orders.cancelOrder': 'Cancel Order',
  'orders.cancelOrderDesc': 'This will cancel the order. This action cannot be undone.',
  'orders.orderConfirmed': 'Order confirmed and license key generated',
  'orders.orderCancelled': 'Order cancelled',
  
  // License Management
  'license.title': 'LICENSE // MANAGEMENT',
  'license.subtitle': 'Create and manage activation keys',
  'license.generateKey': 'Generate Key',
  'license.total': 'Total',
  'license.licenseKeys': 'License Keys',
  'license.allGeneratedKeys': 'All generated license keys',
  'license.licenseKey': 'License Key',
  'license.status': 'Status',
  'license.assignedTo': 'Assigned To',
  'license.activations': 'Activations',
  'license.created': 'Created',
  'license.expires': 'Expires',
  'license.noLicenses': 'No license keys generated yet',
  'license.copyKey': 'Copy Key',
  'license.edit': 'Edit',
  'license.delete': 'Delete',
  'license.generateNew': 'Generate New License Key',
  'license.generateNewDesc': 'Create a new activation key for distribution',
  'license.assignedToOptional': 'Assigned To (Optional)',
  'license.customerName': 'Customer name',
  'license.emailOptional': 'Email (Optional)',
  'license.maxActivations': 'Max Activations',
  'license.initialStatus': 'Initial Status',
  'license.notesOptional': 'Notes (Optional)',
  'license.internalNotes': 'Internal notes about this license',
  'license.cancel': 'Cancel',
  'license.generating': 'Generating...',
  'license.editLicense': 'Edit License',
  'license.editLicenseDesc': 'Update license key details',
  'license.saving': 'Saving...',
  'license.saveChanges': 'Save Changes',
  'license.deleteConfirm': 'Delete License Key?',
  'license.deleteConfirmDesc': 'This action cannot be undone. The license key will be permanently deleted.',
  'license.keyCopied': 'License key copied to clipboard',
  'license.createSuccess': 'License key created successfully',
  'license.updateSuccess': 'License updated successfully',
  'license.deleteSuccess': 'License deleted successfully',
  
  // Security
  'security.title': 'SECURITY // MONITOR',
  'security.subtitle': 'Track and respond to security events',
  'security.totalEvents': 'Total Events',
  'security.unresolved': 'Unresolved',
  'security.critical': 'Critical',
  'security.last24h': 'Last 24h',
  'security.securityEvents': 'Security Events',
  'security.securityEventsDesc': 'Monitor and manage security incidents',
  'security.unresolvedTab': 'Unresolved',
  'security.allEventsTab': 'All Events',
  'security.eventType': 'Event Type',
  'security.severity': 'Severity',
  'security.ipAddress': 'IP Address',
  'security.details': 'Details',
  'security.time': 'Time',
  'security.statusLabel': 'Status',
  'security.noEvents': 'No security events found',
  'security.resolved': 'Resolved',
  'security.open': 'Open',
  'security.resolve': 'Resolve',
  'security.resolveSuccess': 'Event marked as resolved',
  'security.guidelines': 'Security Guidelines',
  'security.bruteForce': 'Brute Force:',
  'security.bruteForceDesc': 'Multiple failed attempts from same IP. Consider blocking the IP address.',
  'security.hwidMismatch': 'HWID Mismatch:',
  'security.hwidMismatchDesc': 'License used on different hardware. Verify with customer.',
  'security.invalidKey': 'Invalid Key:',
  'security.invalidKeyDesc': 'Someone tried a non-existent key. May indicate key guessing.',
  'security.expiredRevoked': 'Expired/Revoked:',
  'security.expiredRevokedDesc': 'Attempted use of invalid license. May need customer follow-up.',
  
  // Settings
  'settings.title': 'SYSTEM // SETTINGS',
  'settings.subtitle': 'Configure application settings and preferences',
  'settings.appDistribution': 'Application Distribution',
  'settings.appDistributionDesc': 'Manage the Windows application download',
  'settings.currentVersion': 'Current Version',
  'settings.totalDownloads': 'Total Downloads',
  'settings.thisWeek': 'This Week',
  'settings.uploadNewVersion': 'Upload New Version',
  'settings.uploadDesc': 'Upload the compiled .exe file to make it available for download on the landing page.',
  'settings.licenseConfig': 'License Configuration',
  'settings.licenseConfigDesc': 'Configure license key settings',
  'settings.totalKeys': 'Total Keys',
  'settings.defaultMaxActivations': 'Default Max Activations',
  'settings.perLicenseKey': 'Per license key',
  'settings.autoExpire': 'Auto-expire after (days)',
  'settings.neverExpire': '0 = never expire',
  'settings.exportLicenses': 'Export All Licenses (CSV)',
  'settings.securitySettings': 'Security Settings',
  'settings.securitySettingsDesc': 'Configure security and monitoring options',
  'settings.bruteForceProtection': 'Brute Force Protection',
  'settings.bruteForceProtectionDesc': 'Block after 5 failed attempts',
  'settings.hwidVerification': 'HWID Verification',
  'settings.hwidVerificationDesc': 'Lock licenses to hardware',
  'settings.ipLogging': 'IP Logging',
  'settings.ipLoggingDesc': 'Track activation IPs',
  'settings.securityEventAlerts': 'Security Event Alerts',
  'settings.securityEventAlertsDesc': 'Email on critical events',
  'settings.notifications': 'Notifications',
  'settings.notificationsDesc': 'Configure alert preferences',
  'settings.newActivations': 'New Activations',
  'settings.newActivationsDesc': 'Notify on successful activations',
  'settings.failedActivations': 'Failed Activations',
  'settings.failedActivationsDesc': 'Alert on failed attempts',
  'settings.securityAlertsNotif': 'Security Alerts',
  'settings.securityAlertsNotifDesc': 'Critical security events',
  'settings.dailySummary': 'Daily Summary',
  'settings.dailySummaryDesc': 'Daily activity report',
  'settings.apiEndpoints': 'API Endpoints',
  'settings.apiEndpointsDesc': 'Endpoints for Windows application integration',
  'settings.licenseValidation': 'License Validation',
  'settings.licenseValidationDesc': 'Validates a license key and returns activation status.',
  'settings.statusReport': 'Status Report',
  'settings.statusReportDesc': 'Reports application status and usage data.',
  'settings.trackDownload': 'Track Download',
  'settings.trackDownloadDesc': 'Tracks application downloads for analytics.',
  'settings.saveSettings': 'Save Settings',
  'settings.settingsSaved': 'Settings saved successfully',
  
  // Auth
  'auth.signInToContinue': 'Sign in to continue',
  'auth.signInDesc': 'Access to this dashboard requires authentication. Continue to launch the login flow.',
  'auth.signIn': 'Sign in',
  'auth.accessDenied': 'ACCESS DENIED',
  'auth.noPermission': 'You do not have permission to access the admin panel.',
  'auth.returnHome': 'Return Home',
  'auth.adminAccessRequired': 'Admin Access Required',
  'auth.adminAccessDesc': 'Sign in with an admin account to access the control panel.',
  
  // Common
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.comingSoon': 'Feature coming soon',
  'common.language': 'Language',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.all': 'All',
  'common.none': 'None',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.view': 'View',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.previous': 'Previous',
};

// Arabic translations
const arTranslations: Record<string, string> = {
  // Navigation
  'nav.adminPanel': 'لوحة الإدارة',
  'nav.welcome': 'مرحباً',
  'nav.dashboard': 'لوحة التحكم',
  'nav.licenses': 'التراخيص',
  'nav.security': 'الأمان',
  'nav.settings': 'الإعدادات',
  'nav.orders': 'الطلبات',
  'nav.backToSite': 'العودة للموقع',
  'nav.signOut': 'تسجيل الخروج',
  'nav.pricing': 'الأسعار',
  'nav.download': 'تحميل',
  'nav.backToHome': 'العودة للرئيسية',
  
  // Landing Page
  'landing.badge': 'نظام كشف الألوان المتقدم',
  'landing.tagline': 'تتبع الألوان الاحترافي والتحكم الآلي بالماوس لنظام ويندوز.',
  'landing.precision': 'دقة. سرعة. تحكم.',
  'landing.download': 'تحميل لويندوز',
  'landing.version': 'الإصدار 1.0.0 • ويندوز 10/11 • 64-بت',
  'landing.featuresTitle': 'النظام // المميزات',
  'landing.featuresSubtitle': 'مصمم للأداء، مبني للدقة',
  'landing.feature.colorDetection': 'كشف الألوان',
  'landing.feature.colorDetectionDesc': 'تتبع الألوان على مستوى البكسل مع تحمل قابل للتخصيص ودعم متعدد الألوان.',
  'landing.feature.instantResponse': 'استجابة فورية',
  'landing.feature.instantResponseDesc': 'كشف بأقل من ميلي ثانية مع خوارزميات محسنة للأداء في الوقت الفعلي.',
  'landing.feature.regionSelection': 'اختيار المنطقة',
  'landing.feature.regionSelectionDesc': 'حدد مناطق شاشة معينة لتحسين الأداء وتقليل الإيجابيات الخاطئة.',
  'landing.feature.fullControl': 'تحكم كامل',
  'landing.feature.fullControlDesc': 'معدلات نقر قابلة للتعديل وحساسية التتبع ومفاتيح اختصار مخصصة.',
  'landing.feature.multiMonitor': 'شاشات متعددة',
  'landing.feature.multiMonitorDesc': 'دعم سلس لإعدادات الشاشات المتعددة مع تتبع منطقة مستقل.',
  'landing.feature.secureLicensing': 'ترخيص آمن',
  'landing.feature.secureLicensingDesc': 'تفعيل مقفل بالأجهزة مع التحقق المشفر من الترخيص.',
  'landing.stats.responseTime': 'وقت الاستجابة',
  'landing.stats.fpsTracking': 'تتبع FPS',
  'landing.stats.accuracy': 'الدقة',
  'landing.stats.support': 'الدعم',
  'landing.cta.title': 'مستعد للسيطرة؟',
  'landing.cta.subtitle': 'حمل KSA,Boom الآن واختبر المستوى التالي من تقنية تتبع الألوان.',
  'landing.cta.button': 'ابدأ الآن',
  'landing.footer': '© 2024 KSA,Boom. جميع الحقوق محفوظة.',
  
  // Pricing Page
  'pricing.badge': 'خطط الاشتراك',
  'pricing.title': 'اختر خطتك',
  'pricing.subtitle': 'اختر الاشتراك الذي يناسب احتياجاتك. جميع الخطط تشمل الوصول الكامل لميزات KSA,Boom.',
  'pricing.weekly': 'الخطة الأسبوعية',
  'pricing.monthly': 'الخطة الشهرية',
  'pricing.yearly': 'الخطة السنوية',
  'pricing.weeklyDesc': 'اشتراك أسبوعي',
  'pricing.monthlyDesc': 'اشتراك شهري',
  'pricing.yearlyDesc': 'اشتراك سنوي',
  'pricing.mostPopular': 'الأكثر شعبية',
  'pricing.getStarted': 'ابدأ الآن',
  'pricing.paymentInfo': 'معلومات الدفع',
  'pricing.paymentDesc': 'بعد تقديم طلبك، سيتواصل فريقنا معك عبر البريد الإلكتروني للتحقق من الدفع. بمجرد التأكيد، سيتم إنشاء مفتاح الترخيص وإرساله إلى بريدك الإلكتروني.',
  'pricing.contactEmail': 'لاستفسارات الدفع، تواصل معنا على:',
  'pricing.orderPlaced': 'تم تقديم الطلب بنجاح!',
  'pricing.orderNumber': 'رقم الطلب',
  'pricing.orderConfirmation': 'لقد استلمنا طلبك. سيتواصل فريقنا معك على البريد الإلكتروني الذي قدمته للتحقق من الدفع.',
  'pricing.whatNext': 'ماذا يحدث بعد ذلك؟',
  'pricing.step1': 'سيتواصل فريقنا معك عبر البريد الإلكتروني',
  'pricing.step2': 'إكمال التحقق من الدفع',
  'pricing.step3': 'استلام مفتاح الترخيص الخاص بك',
  'pricing.placeOrder': 'تقديم الطلب',
  'pricing.processing': 'جاري المعالجة...',
  'pricing.yourEmail': 'بريدك الإلكتروني',
  'pricing.yourName': 'اسمك',
  'pricing.enterEmail': 'أدخل بريدك الإلكتروني',
  'pricing.enterName': 'أدخل اسمك',
  'pricing.close': 'إغلاق',
  
  // Plan Features
  'plan.feature.fullAccess': 'وصول كامل لجميع الميزات',
  'plan.feature.colorDetection': 'كشف الألوان المتقدم',
  'plan.feature.multiMonitor': 'دعم الشاشات المتعددة',
  'plan.feature.customHotkeys': 'مفاتيح اختصار مخصصة',
  'plan.feature.prioritySupport': 'دعم ذو أولوية',
  'plan.feature.updates': 'تحديثات مجانية',
  'plan.feature.hwLock': 'ترخيص مقفل بالأجهزة',
  'plan.feature.emailSupport': 'دعم عبر البريد الإلكتروني',
  'plan.feature.weeklyUpdates': 'تحديثات أسبوعية',
  'plan.feature.monthlyUpdates': 'تحديثات شهرية',
  'plan.feature.yearlyUpdates': 'تحديثات سنوية',
  'plan.feature.basicSupport': 'دعم أساسي',
  'plan.feature.premiumSupport': 'دعم متميز',
  'plan.feature.dedicatedSupport': 'دعم مخصص',
  'plan.feature.allFeatures': 'جميع الميزات المتميزة',
  'plan.feature.unlimitedUse': 'استخدام غير محدود',
  'plan.feature.fastResponse': 'وقت استجابة سريع',
  'plan.feature.regionSelection': 'اختيار المنطقة',
  'plan.feature.clickAutomation': 'أتمتة النقر',
  'plan.feature.bestValue': 'أفضل قيمة',
  
  // Download Page
  'download.title': 'تحميل KSA,Boom',
  'download.subtitle': 'احصل على أحدث إصدار من KSA,Boom لويندوز',
  'download.downloadNow': 'تحميل الآن',
  'download.version': 'الإصدار',
  'download.size': 'الحجم',
  'download.platform': 'المنصة',
  'download.requirements': 'متطلبات النظام',
  'download.os': 'نظام التشغيل',
  'download.osValue': 'ويندوز 10/11 (64-بت)',
  'download.processor': 'المعالج',
  'download.processorValue': 'Intel Core i3 أو ما يعادله',
  'download.memory': 'الذاكرة',
  'download.memoryValue': '4 جيجابايت رام',
  'download.storage': 'التخزين',
  'download.storageValue': '100 ميجابايت مساحة متاحة',
  'download.installation': 'دليل التثبيت',
  'download.step1': 'تحميل المثبت',
  'download.step2': 'تشغيل ملف .exe',
  'download.step3': 'اتبع معالج التثبيت',
  'download.step4': 'أدخل مفتاح الترخيص عند الطلب',
  'download.noLicense': 'ليس لديك مفتاح ترخيص؟',
  'download.getPlan': 'احصل على خطة اشتراك',
  'download.validateLicense': 'التحقق من الترخيص',
  'download.enterLicenseKey': 'أدخل مفتاح الترخيص',
  'download.validate': 'تحقق',
  'download.validating': 'جاري التحقق...',
  'download.licenseValid': 'الترخيص صالح',
  'download.licenseInvalid': 'الترخيص غير صالح',
  'download.expiresOn': 'ينتهي في',
  'download.activationsRemaining': 'تفعيلات متبقية',
  'download.downloadStarting': 'سيبدأ التحميل قريباً...',
  'download.contactAdmin': 'يرجى التواصل مع المسؤول لاستلام ملف التطبيق.',
  
  // Dashboard
  'dashboard.title': 'لوحة // التحكم',
  'dashboard.subtitle': 'نظرة عامة على النظام والمراقبة',
  'dashboard.totalLicenses': 'إجمالي التراخيص',
  'dashboard.downloads': 'التحميلات',
  'dashboard.securityEvents': 'أحداث الأمان',
  'dashboard.pendingOrders': 'الطلبات المعلقة',
  'dashboard.revenue': 'الإيرادات',
  'dashboard.active': 'نشط',
  'dashboard.pending': 'معلق',
  'dashboard.expired': 'منتهي',
  'dashboard.revoked': 'ملغى',
  'dashboard.recentActivations': 'التفعيلات الأخيرة',
  'dashboard.recentActivationsDesc': 'أحدث محاولات تفعيل الترخيص',
  'dashboard.securityAlerts': 'تنبيهات الأمان',
  'dashboard.securityAlertsDesc': 'أحداث الأمان غير المحلولة',
  'dashboard.noRecentActivations': 'لا توجد تفعيلات حديثة',
  'dashboard.noSecurityEvents': 'لا توجد أحداث أمان غير محلولة',
  'dashboard.success': 'نجاح',
  'dashboard.failed': 'فشل',
  'dashboard.unknownDevice': 'جهاز غير معروف',
  'dashboard.today': 'اليوم',
  'dashboard.critical': 'حرج',
  'dashboard.securityEventsLabel': 'أحداث الأمان',
  
  // Orders
  'orders.title': 'إدارة // الطلبات',
  'orders.subtitle': 'إدارة طلبات العملاء والاشتراكات',
  'orders.allOrders': 'جميع الطلبات',
  'orders.pendingOrders': 'معلق',
  'orders.confirmedOrders': 'مؤكد',
  'orders.cancelledOrders': 'ملغى',
  'orders.orderNumber': 'رقم الطلب',
  'orders.customer': 'العميل',
  'orders.plan': 'الخطة',
  'orders.amount': 'المبلغ',
  'orders.status': 'الحالة',
  'orders.date': 'التاريخ',
  'orders.actions': 'الإجراءات',
  'orders.confirm': 'تأكيد',
  'orders.cancel': 'إلغاء',
  'orders.noOrders': 'لا توجد طلبات',
  'orders.confirmOrder': 'تأكيد الطلب',
  'orders.confirmOrderDesc': 'سيتم إنشاء مفتاح ترخيص وإرساله للعميل.',
  'orders.cancelOrder': 'إلغاء الطلب',
  'orders.cancelOrderDesc': 'سيتم إلغاء الطلب. لا يمكن التراجع عن هذا الإجراء.',
  'orders.orderConfirmed': 'تم تأكيد الطلب وإنشاء مفتاح الترخيص',
  'orders.orderCancelled': 'تم إلغاء الطلب',
  
  // License Management
  'license.title': 'إدارة // التراخيص',
  'license.subtitle': 'إنشاء وإدارة مفاتيح التفعيل',
  'license.generateKey': 'إنشاء مفتاح',
  'license.total': 'الإجمالي',
  'license.licenseKeys': 'مفاتيح الترخيص',
  'license.allGeneratedKeys': 'جميع مفاتيح الترخيص المنشأة',
  'license.licenseKey': 'مفتاح الترخيص',
  'license.status': 'الحالة',
  'license.assignedTo': 'مخصص لـ',
  'license.activations': 'التفعيلات',
  'license.created': 'تاريخ الإنشاء',
  'license.expires': 'ينتهي',
  'license.noLicenses': 'لم يتم إنشاء مفاتيح ترخيص بعد',
  'license.copyKey': 'نسخ المفتاح',
  'license.edit': 'تعديل',
  'license.delete': 'حذف',
  'license.generateNew': 'إنشاء مفتاح ترخيص جديد',
  'license.generateNewDesc': 'إنشاء مفتاح تفعيل جديد للتوزيع',
  'license.assignedToOptional': 'مخصص لـ (اختياري)',
  'license.customerName': 'اسم العميل',
  'license.emailOptional': 'البريد الإلكتروني (اختياري)',
  'license.maxActivations': 'الحد الأقصى للتفعيلات',
  'license.initialStatus': 'الحالة الأولية',
  'license.notesOptional': 'ملاحظات (اختياري)',
  'license.internalNotes': 'ملاحظات داخلية حول هذا الترخيص',
  'license.cancel': 'إلغاء',
  'license.generating': 'جاري الإنشاء...',
  'license.editLicense': 'تعديل الترخيص',
  'license.editLicenseDesc': 'تحديث تفاصيل مفتاح الترخيص',
  'license.saving': 'جاري الحفظ...',
  'license.saveChanges': 'حفظ التغييرات',
  'license.deleteConfirm': 'حذف مفتاح الترخيص؟',
  'license.deleteConfirmDesc': 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف مفتاح الترخيص نهائياً.',
  'license.keyCopied': 'تم نسخ مفتاح الترخيص',
  'license.createSuccess': 'تم إنشاء مفتاح الترخيص بنجاح',
  'license.updateSuccess': 'تم تحديث الترخيص بنجاح',
  'license.deleteSuccess': 'تم حذف الترخيص بنجاح',
  
  // Security
  'security.title': 'مراقبة // الأمان',
  'security.subtitle': 'تتبع والاستجابة لأحداث الأمان',
  'security.totalEvents': 'إجمالي الأحداث',
  'security.unresolved': 'غير محلول',
  'security.critical': 'حرج',
  'security.last24h': 'آخر 24 ساعة',
  'security.securityEvents': 'أحداث الأمان',
  'security.securityEventsDesc': 'مراقبة وإدارة حوادث الأمان',
  'security.unresolvedTab': 'غير محلول',
  'security.allEventsTab': 'جميع الأحداث',
  'security.eventType': 'نوع الحدث',
  'security.severity': 'الخطورة',
  'security.ipAddress': 'عنوان IP',
  'security.details': 'التفاصيل',
  'security.time': 'الوقت',
  'security.statusLabel': 'الحالة',
  'security.noEvents': 'لا توجد أحداث أمان',
  'security.resolved': 'محلول',
  'security.open': 'مفتوح',
  'security.resolve': 'حل',
  'security.resolveSuccess': 'تم وضع علامة محلول على الحدث',
  'security.guidelines': 'إرشادات الأمان',
  'security.bruteForce': 'هجوم القوة الغاشمة:',
  'security.bruteForceDesc': 'محاولات فاشلة متعددة من نفس IP. فكر في حظر عنوان IP.',
  'security.hwidMismatch': 'عدم تطابق HWID:',
  'security.hwidMismatchDesc': 'تم استخدام الترخيص على جهاز مختلف. تحقق مع العميل.',
  'security.invalidKey': 'مفتاح غير صالح:',
  'security.invalidKeyDesc': 'حاول شخص ما استخدام مفتاح غير موجود. قد يشير إلى تخمين المفاتيح.',
  'security.expiredRevoked': 'منتهي/ملغى:',
  'security.expiredRevokedDesc': 'محاولة استخدام ترخيص غير صالح. قد يحتاج متابعة مع العميل.',
  
  // Settings
  'settings.title': 'إعدادات // النظام',
  'settings.subtitle': 'تكوين إعدادات التطبيق والتفضيلات',
  'settings.appDistribution': 'توزيع التطبيق',
  'settings.appDistributionDesc': 'إدارة تحميل تطبيق ويندوز',
  'settings.currentVersion': 'الإصدار الحالي',
  'settings.totalDownloads': 'إجمالي التحميلات',
  'settings.thisWeek': 'هذا الأسبوع',
  'settings.uploadNewVersion': 'رفع إصدار جديد',
  'settings.uploadDesc': 'ارفع ملف .exe المترجم لإتاحته للتحميل على الصفحة الرئيسية.',
  'settings.licenseConfig': 'تكوين التراخيص',
  'settings.licenseConfigDesc': 'تكوين إعدادات مفاتيح الترخيص',
  'settings.totalKeys': 'إجمالي المفاتيح',
  'settings.defaultMaxActivations': 'الحد الأقصى الافتراضي للتفعيلات',
  'settings.perLicenseKey': 'لكل مفتاح ترخيص',
  'settings.autoExpire': 'انتهاء تلقائي بعد (أيام)',
  'settings.neverExpire': '0 = لا ينتهي أبداً',
  'settings.exportLicenses': 'تصدير جميع التراخيص (CSV)',
  'settings.securitySettings': 'إعدادات الأمان',
  'settings.securitySettingsDesc': 'تكوين خيارات الأمان والمراقبة',
  'settings.bruteForceProtection': 'حماية من القوة الغاشمة',
  'settings.bruteForceProtectionDesc': 'حظر بعد 5 محاولات فاشلة',
  'settings.hwidVerification': 'التحقق من HWID',
  'settings.hwidVerificationDesc': 'قفل التراخيص بالأجهزة',
  'settings.ipLogging': 'تسجيل IP',
  'settings.ipLoggingDesc': 'تتبع عناوين IP التفعيل',
  'settings.securityEventAlerts': 'تنبيهات أحداث الأمان',
  'settings.securityEventAlertsDesc': 'بريد إلكتروني عند الأحداث الحرجة',
  'settings.notifications': 'الإشعارات',
  'settings.notificationsDesc': 'تكوين تفضيلات التنبيهات',
  'settings.newActivations': 'التفعيلات الجديدة',
  'settings.newActivationsDesc': 'إشعار عند التفعيلات الناجحة',
  'settings.failedActivations': 'التفعيلات الفاشلة',
  'settings.failedActivationsDesc': 'تنبيه عند المحاولات الفاشلة',
  'settings.securityAlertsNotif': 'تنبيهات الأمان',
  'settings.securityAlertsNotifDesc': 'أحداث الأمان الحرجة',
  'settings.dailySummary': 'الملخص اليومي',
  'settings.dailySummaryDesc': 'تقرير النشاط اليومي',
  'settings.apiEndpoints': 'نقاط نهاية API',
  'settings.apiEndpointsDesc': 'نقاط النهاية لتكامل تطبيق ويندوز',
  'settings.licenseValidation': 'التحقق من الترخيص',
  'settings.licenseValidationDesc': 'يتحقق من مفتاح الترخيص ويعيد حالة التفعيل.',
  'settings.statusReport': 'تقرير الحالة',
  'settings.statusReportDesc': 'يبلغ عن حالة التطبيق وبيانات الاستخدام.',
  'settings.trackDownload': 'تتبع التحميل',
  'settings.trackDownloadDesc': 'يتتبع تحميلات التطبيق للتحليلات.',
  'settings.saveSettings': 'حفظ الإعدادات',
  'settings.settingsSaved': 'تم حفظ الإعدادات بنجاح',
  
  // Auth
  'auth.signInToContinue': 'سجل الدخول للمتابعة',
  'auth.signInDesc': 'الوصول إلى لوحة التحكم يتطلب المصادقة. تابع لبدء تسجيل الدخول.',
  'auth.signIn': 'تسجيل الدخول',
  'auth.accessDenied': 'تم رفض الوصول',
  'auth.noPermission': 'ليس لديك إذن للوصول إلى لوحة الإدارة.',
  'auth.returnHome': 'العودة للرئيسية',
  'auth.adminAccessRequired': 'مطلوب صلاحيات المسؤول',
  'auth.adminAccessDesc': 'سجل الدخول بحساب مسؤول للوصول إلى لوحة التحكم.',
  
  // Common
  'common.loading': 'جاري التحميل...',
  'common.error': 'خطأ',
  'common.success': 'نجاح',
  'common.comingSoon': 'الميزة قادمة قريباً',
  'common.language': 'اللغة',
  'common.search': 'بحث',
  'common.filter': 'تصفية',
  'common.all': 'الكل',
  'common.none': 'لا شيء',
  'common.yes': 'نعم',
  'common.no': 'لا',
  'common.save': 'حفظ',
  'common.cancel': 'إلغاء',
  'common.delete': 'حذف',
  'common.edit': 'تعديل',
  'common.view': 'عرض',
  'common.close': 'إغلاق',
  'common.confirm': 'تأكيد',
  'common.back': 'رجوع',
  'common.next': 'التالي',
  'common.previous': 'السابق',
};

// All translations
const translations: Record<string, Record<string, string>> = {
  en: enTranslations,
  ar: arTranslations,
};

// Helper to copy English translations as base for other languages
function createTranslationsFromEnglish(overrides: Record<string, string>): Record<string, string> {
  return { ...enTranslations, ...overrides };
}

// Add translations for other languages with complete coverage
translations.zh = createTranslationsFromEnglish({
  'nav.adminPanel': '管理面板',
  'nav.welcome': '欢迎',
  'nav.dashboard': '仪表板',
  'nav.licenses': '许可证',
  'nav.security': '安全',
  'nav.settings': '设置',
  'nav.orders': '订单',
  'nav.backToSite': '返回网站',
  'nav.signOut': '退出登录',
  'nav.pricing': '价格',
  'nav.download': '下载',
  'nav.backToHome': '返回首页',
  'landing.badge': '高级颜色检测系统',
  'landing.tagline': '专业级颜色追踪和Windows自动鼠标控制。',
  'landing.precision': '精准。速度。控制。',
  'landing.download': '下载Windows版',
  'landing.featuresTitle': '系统 // 功能',
  'landing.featuresSubtitle': '为性能而设计，为精准而打造',
  'landing.cta.title': '准备好称霸了吗？',
  'landing.cta.button': '开始使用',
  'dashboard.title': '控制 // 面板',
  'dashboard.subtitle': '系统概览和监控',
  'pricing.title': '选择您的计划',
  'pricing.subtitle': '选择适合您需求的订阅。所有计划都包含完整的KSA,Boom功能访问。',
  'pricing.getStarted': '开始使用',
  'common.language': '语言',
});

translations.es = createTranslationsFromEnglish({
  'nav.adminPanel': 'Panel de Admin',
  'nav.welcome': 'Bienvenido',
  'nav.dashboard': 'Panel',
  'nav.licenses': 'Licencias',
  'nav.security': 'Seguridad',
  'nav.settings': 'Configuración',
  'nav.orders': 'Pedidos',
  'nav.backToSite': 'Volver al Sitio',
  'nav.signOut': 'Cerrar Sesión',
  'nav.pricing': 'Precios',
  'nav.download': 'Descargar',
  'nav.backToHome': 'Volver al Inicio',
  'landing.badge': 'SISTEMA AVANZADO DE DETECCIÓN DE COLOR',
  'landing.tagline': 'Seguimiento de color profesional y control automático del ratón para Windows.',
  'landing.precision': 'Precisión. Velocidad. Control.',
  'landing.download': 'DESCARGAR PARA WINDOWS',
  'landing.featuresTitle': 'SISTEMA // CARACTERÍSTICAS',
  'landing.featuresSubtitle': 'Diseñado para el rendimiento, construido para la precisión',
  'landing.cta.title': '¿Listo para Dominar?',
  'landing.cta.button': 'COMENZAR',
  'dashboard.title': 'PANEL // DE CONTROL',
  'dashboard.subtitle': 'Vista general del sistema y monitoreo',
  'pricing.title': 'Elige Tu Plan',
  'pricing.subtitle': 'Selecciona la suscripción que se adapte a tus necesidades.',
  'pricing.getStarted': 'Comenzar',
  'common.language': 'Idioma',
});

translations.fr = createTranslationsFromEnglish({
  'nav.adminPanel': 'Panneau Admin',
  'nav.welcome': 'Bienvenue',
  'nav.dashboard': 'Tableau de Bord',
  'nav.licenses': 'Licences',
  'nav.security': 'Sécurité',
  'nav.settings': 'Paramètres',
  'nav.orders': 'Commandes',
  'nav.backToSite': 'Retour au Site',
  'nav.signOut': 'Déconnexion',
  'nav.pricing': 'Tarifs',
  'nav.download': 'Télécharger',
  'nav.backToHome': 'Retour à l\'Accueil',
  'landing.badge': 'SYSTÈME DE DÉTECTION DE COULEUR AVANCÉ',
  'landing.tagline': 'Suivi de couleur professionnel et contrôle automatique de la souris pour Windows.',
  'landing.precision': 'Précision. Vitesse. Contrôle.',
  'landing.download': 'TÉLÉCHARGER POUR WINDOWS',
  'landing.featuresTitle': 'SYSTÈME // FONCTIONNALITÉS',
  'landing.featuresSubtitle': 'Conçu pour la performance, construit pour la précision',
  'landing.cta.title': 'Prêt à Dominer?',
  'landing.cta.button': 'COMMENCER',
  'dashboard.title': 'PANNEAU // DE CONTRÔLE',
  'dashboard.subtitle': 'Vue d\'ensemble du système et surveillance',
  'pricing.title': 'Choisissez Votre Plan',
  'pricing.subtitle': 'Sélectionnez l\'abonnement qui correspond à vos besoins.',
  'pricing.getStarted': 'Commencer',
  'common.language': 'Langue',
});

translations.de = createTranslationsFromEnglish({
  'nav.adminPanel': 'Admin-Panel',
  'nav.welcome': 'Willkommen',
  'nav.dashboard': 'Dashboard',
  'nav.licenses': 'Lizenzen',
  'nav.security': 'Sicherheit',
  'nav.settings': 'Einstellungen',
  'nav.orders': 'Bestellungen',
  'nav.backToSite': 'Zurück zur Seite',
  'nav.signOut': 'Abmelden',
  'nav.pricing': 'Preise',
  'nav.download': 'Herunterladen',
  'nav.backToHome': 'Zurück zur Startseite',
  'landing.badge': 'FORTSCHRITTLICHES FARBERKENNUNGSSYSTEM',
  'landing.tagline': 'Professionelle Farbverfolgung und automatische Maussteuerung für Windows.',
  'landing.precision': 'Präzision. Geschwindigkeit. Kontrolle.',
  'landing.download': 'FÜR WINDOWS HERUNTERLADEN',
  'landing.featuresTitle': 'SYSTEM // FUNKTIONEN',
  'landing.featuresSubtitle': 'Entwickelt für Leistung, gebaut für Präzision',
  'landing.cta.title': 'Bereit zu Dominieren?',
  'landing.cta.button': 'LOSLEGEN',
  'dashboard.title': 'KONTROLL // PANEL',
  'dashboard.subtitle': 'Systemübersicht und Überwachung',
  'pricing.title': 'Wählen Sie Ihren Plan',
  'pricing.subtitle': 'Wählen Sie das Abonnement, das Ihren Bedürfnissen entspricht.',
  'pricing.getStarted': 'Loslegen',
  'common.language': 'Sprache',
});

translations.ja = createTranslationsFromEnglish({
  'nav.adminPanel': '管理パネル',
  'nav.welcome': 'ようこそ',
  'nav.dashboard': 'ダッシュボード',
  'nav.licenses': 'ライセンス',
  'nav.security': 'セキュリティ',
  'nav.settings': '設定',
  'nav.orders': '注文',
  'nav.backToSite': 'サイトに戻る',
  'nav.signOut': 'ログアウト',
  'nav.pricing': '料金',
  'nav.download': 'ダウンロード',
  'nav.backToHome': 'ホームに戻る',
  'landing.badge': '高度なカラー検出システム',
  'landing.tagline': 'Windows用プロフェッショナルグレードのカラートラッキングと自動マウス制御。',
  'landing.precision': '精度。速度。制御。',
  'landing.download': 'WINDOWS版をダウンロード',
  'landing.featuresTitle': 'システム // 機能',
  'landing.featuresSubtitle': 'パフォーマンスのために設計、精度のために構築',
  'landing.cta.title': '支配する準備はできましたか？',
  'landing.cta.button': '始める',
  'dashboard.title': 'コントロール // パネル',
  'dashboard.subtitle': 'システム概要と監視',
  'pricing.title': 'プランを選択',
  'pricing.subtitle': 'ニーズに合ったサブスクリプションを選択してください。',
  'pricing.getStarted': '始める',
  'common.language': '言語',
});

translations.ko = createTranslationsFromEnglish({
  'nav.adminPanel': '관리자 패널',
  'nav.welcome': '환영합니다',
  'nav.dashboard': '대시보드',
  'nav.licenses': '라이선스',
  'nav.security': '보안',
  'nav.settings': '설정',
  'nav.orders': '주문',
  'nav.backToSite': '사이트로 돌아가기',
  'nav.signOut': '로그아웃',
  'nav.pricing': '가격',
  'nav.download': '다운로드',
  'nav.backToHome': '홈으로 돌아가기',
  'landing.badge': '고급 색상 감지 시스템',
  'landing.tagline': 'Windows용 전문가급 색상 추적 및 자동 마우스 제어.',
  'landing.precision': '정밀함. 속도. 제어.',
  'landing.download': 'WINDOWS용 다운로드',
  'landing.featuresTitle': '시스템 // 기능',
  'landing.featuresSubtitle': '성능을 위해 설계, 정밀함을 위해 구축',
  'landing.cta.title': '지배할 준비가 되셨나요?',
  'landing.cta.button': '시작하기',
  'dashboard.title': '컨트롤 // 패널',
  'dashboard.subtitle': '시스템 개요 및 모니터링',
  'pricing.title': '플랜 선택',
  'pricing.subtitle': '필요에 맞는 구독을 선택하세요.',
  'pricing.getStarted': '시작하기',
  'common.language': '언어',
});

translations.ru = createTranslationsFromEnglish({
  'nav.adminPanel': 'Панель Админа',
  'nav.welcome': 'Добро пожаловать',
  'nav.dashboard': 'Панель управления',
  'nav.licenses': 'Лицензии',
  'nav.security': 'Безопасность',
  'nav.settings': 'Настройки',
  'nav.orders': 'Заказы',
  'nav.backToSite': 'Вернуться на сайт',
  'nav.signOut': 'Выйти',
  'nav.pricing': 'Цены',
  'nav.download': 'Скачать',
  'nav.backToHome': 'На главную',
  'landing.badge': 'ПРОДВИНУТАЯ СИСТЕМА ОПРЕДЕЛЕНИЯ ЦВЕТА',
  'landing.tagline': 'Профессиональное отслеживание цвета и автоматическое управление мышью для Windows.',
  'landing.precision': 'Точность. Скорость. Контроль.',
  'landing.download': 'СКАЧАТЬ ДЛЯ WINDOWS',
  'landing.featuresTitle': 'СИСТЕМА // ФУНКЦИИ',
  'landing.featuresSubtitle': 'Разработано для производительности, создано для точности',
  'landing.cta.title': 'Готовы Доминировать?',
  'landing.cta.button': 'НАЧАТЬ',
  'dashboard.title': 'ПАНЕЛЬ // УПРАВЛЕНИЯ',
  'dashboard.subtitle': 'Обзор системы и мониторинг',
  'pricing.title': 'Выберите Ваш План',
  'pricing.subtitle': 'Выберите подписку, которая соответствует вашим потребностям.',
  'pricing.getStarted': 'Начать',
  'common.language': 'Язык',
});

translations.tr = createTranslationsFromEnglish({
  'nav.adminPanel': 'Yönetici Paneli',
  'nav.welcome': 'Hoş Geldiniz',
  'nav.dashboard': 'Gösterge Paneli',
  'nav.licenses': 'Lisanslar',
  'nav.security': 'Güvenlik',
  'nav.settings': 'Ayarlar',
  'nav.orders': 'Siparişler',
  'nav.backToSite': 'Siteye Dön',
  'nav.signOut': 'Çıkış Yap',
  'nav.pricing': 'Fiyatlandırma',
  'nav.download': 'İndir',
  'nav.backToHome': 'Ana Sayfaya Dön',
  'landing.badge': 'GELİŞMİŞ RENK ALGILAMA SİSTEMİ',
  'landing.tagline': 'Windows için profesyonel düzeyde renk takibi ve otomatik fare kontrolü.',
  'landing.precision': 'Hassasiyet. Hız. Kontrol.',
  'landing.download': 'WINDOWS İÇİN İNDİR',
  'landing.featuresTitle': 'SİSTEM // ÖZELLİKLER',
  'landing.featuresSubtitle': 'Performans için tasarlandı, hassasiyet için inşa edildi',
  'landing.cta.title': 'Domine Etmeye Hazır mısınız?',
  'landing.cta.button': 'BAŞLA',
  'dashboard.title': 'KONTROL // PANELİ',
  'dashboard.subtitle': 'Sistem genel bakış ve izleme',
  'pricing.title': 'Planınızı Seçin',
  'pricing.subtitle': 'İhtiyaçlarınıza uygun aboneliği seçin.',
  'pricing.getStarted': 'Başla',
  'common.language': 'Dil',
});

translations.pt = createTranslationsFromEnglish({
  'nav.adminPanel': 'Painel Admin',
  'nav.welcome': 'Bem-vindo',
  'nav.dashboard': 'Painel',
  'nav.licenses': 'Licenças',
  'nav.security': 'Segurança',
  'nav.settings': 'Configurações',
  'nav.orders': 'Pedidos',
  'nav.backToSite': 'Voltar ao Site',
  'nav.signOut': 'Sair',
  'nav.pricing': 'Preços',
  'nav.download': 'Baixar',
  'nav.backToHome': 'Voltar ao Início',
  'landing.badge': 'SISTEMA AVANÇADO DE DETECÇÃO DE COR',
  'landing.tagline': 'Rastreamento de cor profissional e controle automático do mouse para Windows.',
  'landing.precision': 'Precisão. Velocidade. Controle.',
  'landing.download': 'BAIXAR PARA WINDOWS',
  'landing.featuresTitle': 'SISTEMA // RECURSOS',
  'landing.featuresSubtitle': 'Projetado para desempenho, construído para precisão',
  'landing.cta.title': 'Pronto para Dominar?',
  'landing.cta.button': 'COMEÇAR',
  'dashboard.title': 'PAINEL // DE CONTROLE',
  'dashboard.subtitle': 'Visão geral do sistema e monitoramento',
  'pricing.title': 'Escolha Seu Plano',
  'pricing.subtitle': 'Selecione a assinatura que atende às suas necessidades.',
  'pricing.getStarted': 'Começar',
  'common.language': 'Idioma',
});

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'ksa-boom-language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved && saved in SUPPORTED_LANGUAGES) {
        return saved as LanguageCode;
      }
      // Try to detect browser language
      const browserLang = navigator.language.split('-')[0];
      if (browserLang in SUPPORTED_LANGUAGES) {
        return browserLang as LanguageCode;
      }
    }
    return 'en';
  });

  const isRTL = (SUPPORTED_LANGUAGES[language] as { rtl?: boolean })?.rtl === true;

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    // Update document direction for RTL languages
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback((key: string, params?: Record<string, string | number>): string => {
    // Get translation from current language or fallback to English
    let text = translations[language]?.[key] || translations.en[key] || key;
    
    // Replace parameters if provided
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(new RegExp(`{{${param}}}`, 'g'), String(value));
      });
    }
    
    return text;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
